version: '3.9'

services:

  mt:
    build:
      context: .
    restart: unless-stopped
    # runtime: nvidia  # Comment out in local
    ports:
      - 8000:8000
    volumes:
      - .:/app
      # - ./models:/app/models
      - ./config.json:/app/config.json
    environment:
      - MT_API_CONFIG=/app/config.json
      # - MT_API_DEVICE=gpu #or gpu, if so make runtime:nvidia
      - MT_API_THREADS=16
      - MODELS_ROOT=/app/models
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all

